### ISSUE TITLE
Can't connect from unlegit client

### ISSUE THREAD

**Issue by T0MuX** [hpoon/HLDS-CS1.6#2]
Hi, I successfully installed this on my server, and it works super well with my Counter Strike legit client (from Steam). But, it doesn't work at all from an unlegit client (like Counter Strike WarZone or what).

I look at the web for a solution, but can't find anything on that. It seems to be more complicated than I though, I was thinking it was just a setting you know, like "sv_blabla_legit 0" but nothing.

Maybe you have a solution or a simple explanation ? Thank you by advance

**Comment by hpoon** [comment]
Sorry this isn't supported
